### ISSUE TITLE
README example doesn't work in Node anymore because of solid-auth-client

### ISSUE THREAD

**Issue by RubenVerborgh** [RubenVerborgh/LDflex#35]
```
(node:13449) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at currentUrl (/Users/ruben/Documents/JavaScript/LDflex/node_modules/solid-auth-client/lib/url-util.js:9:42)
    at toUrlString (/Users/ruben/Documents/JavaScript/LDflex/node_modules/solid-auth-client/lib/url-util.js:32:23)
    at SolidAuthClient.fetch (/Users/ruben/Documents/JavaScript/LDflex/node_modules/solid-auth-client/lib/solid-auth-client.js:41:51)
    at ActorHttpSolidAuthFetch.run (/Users/ruben/Documents/JavaScript/LDflex/node_modules/@comunica/actor-http-solid-auth-fetch/lib/ActorHttpSolidAuthFetch.js:13:22)
    at ActorHttpSolidAuthFetch.runObservable (/Users/ruben/Documents/JavaScript/LDflex/node_modules/@comunica/core/lib/Actor.js:53:29)
    at MediatorNumber.mediate (/Users/ruben/Documents/JavaScript/LDflex/node_modules/@comunica/core/lib/Mediator.js:80:22)
(node:13449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 91)
(node:13449) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rubensworks** [comment]
This was reported in https://github.com/RubenVerborgh/LDflex-Comunica/issues/12 as well. But no fix is available yet.

**Comment by RubenVerborgh** [comment]
Fixing in https://github.com/RubenVerborgh/LDflex-Comunica/issues/12
